#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=300G
#SBATCH --time=3-0:00:00
#SBATCH --output=/rhome/auyeh/bigdata/H_mur/results/Hmur_012_fltrBcftools2.stdout
#SBATCH --error=/rhome/auyeh/bigdata/H_mur/results/Hmur_012_fltrBcftools2.stderr
#SBATCH --mail-user=auyeh002@ucr.edu
#SBATCH --mail-type=ALL
#SBATCH --job-name="fltS2!!"
#SBATCH -p highmem

module load bcftools/1.8

#make list of DP (Read depth @ position) to set initial filtering values
#bcftools query -f '%CHROM\t%POS\t[%DP]\n' hmur_snps_varscan_flt1.vcf > PostnReadDepth_flt1.txt

#after filter 1, check distribution of AD, FREQ, ABQ
#bcftools query -f '%CHROM\t%POS\t[%RDF]\t[%RDR]\t[%ADF]\t[%ADR]\n' hmur_snps_varscan_flt1.vcf > AD_FREQ_ABQ_f1.txt

#count variants remaining
#grep -c "^chr" hmur_raw_snps_varscan.vcf


#run a filter on DP and N_ALT=1
cd /rhome/auyeh/bigdata/H_mur/results/aligned/

bcftools view -e 'ABQ<30' -o hmur_snps_varscan_flt2.vcf hmur_snps_varscan_flt1.vcf

echo "Variant count after filter2-- exclude ABQ<30"
grep -c "^chr" hmur_snps_varscan_flt2.vcf

echo "Number of variants = reference & fixed... creating txt file"
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t[%RD]\t[%AD]\n' hmur_snps_varscan_flt2.vcf > RD_AD_f2.txt

echo "...creating vcf file for fixed and NOT reference"
bcftools view -i 'FREQ>99 & AD>0' -o hmur_fixed_ntREF.vcf hmur_snps_varscan_flt2.vcf

echo "...creating vcf file for fixed AND reference"
bcftools view -i 'FREQ>99 & RD>0' -o hmur_fixed_REF.vcf hmur_snps_varscan_flt2.vcf
