#!/bin/bash -l

#SBATCH --array=1-4
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --mem=264G
#SBATCH --time=1-00:00:00
#SBATCH --output=/rhome/auyeh/bigdata/H_mur/results/Hmur_004_stampytest_align.stdout
#SBATCH --mail-user=auyeh002@ucr.edu
#SBATCH --mail-type=ALL
#SBATCH --job-name="H_mur_testalign"
#SBATCH -p intel 	 #Options:  intel, batch, highmem (200 Gb memory), gpu, short (jobs with wall time of 2 h) check with squeue -p PARTITIONNAME



#216 hours

zcat /rhome/auyeh/bigdata/H_mur/results/hmur_lane1pair1_forward_paired.fq.gz | split -l 4000000 /rhome/auyeh/bigdata/H_mur/results/hmur_paired_split/hmur_F_paired_
zcat /rhome/auyeh/bigdata/H_mur/results/hmur_lane1pair2_reverse_paired.fq.gz | split -l 4000000 /rhome/auyeh/bigdata/H_mur/results/hmur_paired_split/hmur_R_paired_


module load bwa/0.7.17
module load samtools/1.9
module load stampy/1.0.2

#hmur_paired_split
HPS=/rhome/auyeh/bigdata/H_mur/results/hmur_paired_split
cd $HPS

SEQLIST_F=/rhome/auyeh/bigdata/H_mur/results/filelists/SEQLIST_F
SEQLIST_R=/rhome/auyeh/bigdata/H_mur/results/filelists/SEQLIST_R

ls hmur_F_paired_* > $SEQLIST_F
ls hmur_R_paired_* > $SEQLIST_R

FILE_F=$(head -n $SLURM_ARRAY_TASK_ID $SEQLIST_F | tail -n 1 )
FILE_R=$(head -n $SLURM_ARRAY_TASK_ID $SEQLIST_R | tail -n 1 )

echo $FILE_F
echo $FILE_R

module load bwa/0.7.17
bwa mem -R "@RG\tID:Hordeum_murinum_AG196-2_ATCACG\tSM:AG196-2\tPU:ATCACG_flowcell718_lane1\tLB:lib1\tPL:ILLUMINA" -t 5 /rhome/auyeh/bigdata/H_mur/results/aligned/bwa_barley_split_ref $FILE_F $FILE_R > hmur_bwa_"$SLURM_ARRAY_TASK_ID".sam
module load samtools/1.9
samtools view -b hmur_bwa_"$SLURM_ARRAY_TASK_ID".sam > hmur_bwa_"$SLURM_ARRAY_TASK_ID".bam

OUTDIR=/rhome/auyeh/bigdata/H_mur/results/aligned
/opt/linux/centos/7.x/x86_64/pkgs/stampy/1.0.28/stampy.py -g $OUTDIR/splitbarley_ref -h $OUTDIR/splitbarley_ref_h -t 5 --substitutionrate=0.01 --bamkeepgoodreads -M hmur_bwa_"$SLURM_ARRAY_TASK_ID".bam -o $OUTDIR/"$FILE_F".sam -f sam | \
samtools sort -o $OUTDIR/"$FILE_F"_sorted.bam -



/opt/linux/centos/7.x/x86_64/pkgs/stampy/1.0.28/stampy.py -g /rhome/auyeh/bigdata/H_mur/results/aligned/splitbarley_ref -h /rhome/auyeh/bigdata/H_mur/results/aligned/splitbarley_ref_h -t 5 --substitutionrate=0.01 --bamkeepgoodreads -M /rhome/auyeh/bigdata/H_mur/results/hmur_paired_split/hmur_bwa_1.bam -o /rhome/auyeh/bigdata/H_mur/results/aligned/TEST.sam -f sam | samtools sort -o /rhome/auyeh/bigdata/H_mur/results/aligned/TEST_sorted.bam
